version: '3'
services:
  db:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
      - ./docker/db/conf.d:/etc/mysql/conf.d
    networks:
      - my-digital-nomads
    ports:
      - "33080:3306"
volumes:
  db_data:
    driver: "local"
networks:
    my-digital-nomads:
        driver: "bridge"
